---
- name: Local setup playbook
  hosts: localhost
  connection: local
  vars_files:
    # Overriden by config.yml
    - "{{ playbook_dir }}/default.config.yml"
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    local_home: "{{ lookup('env', 'HOME') }}"
    #   data_dir: "{{ local_home }}/.local/share"
    os_family: "{{ ansible_os_family | lower }}"
  # environment:
  #   GEM_HOME: "{{ data_dir }}/gem"

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Get facts about the host
      ansible.builtin.setup:
        gather_subset: all
      register: host_facts

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        ansible_distribution: "{{ host_facts['ansible_facts']['ansible_distribution'] }}"
        is_macos: "{{ os_family == 'darwin' }}"
        is_debian: "{{ os_family == 'debian' }}"
        cacheable: false

    - name: Print detected OS
      ansible.builtin.debug:
        msg: "is_macos = {{ is_macos }}"

  tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Done!
      ansible.builtin.debug:
        msg: "Finished the playbook!"

  roles:
    - role: setup
    # vars:
    #   setup_dir: '/opt/a'
    #   setup_app_port: 5000
    # tags: typeA
    - role: macos
      when: is_macos
    - role: debian
      when: is_debian
    - role: unix
      when: is_debian or is_macos
