---
- name: Local setup playbook
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

  # vars:
  #   some_variable: "value"

  tasks:

    - name: Get facts about the host
      ansible.builtin.setup:
        gather_subset: all
      register: host_facts

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        username_on_the_host: "{{ host_facts['ansible_facts']['ansible_env']['SUDO_USER'] }}"
      # - name: Test
      #   ansible.builtin.debug:
      #     var: host_facts
      #     var: username_on_the_host


    # - name: Starting playbook
    #   ansible.builtin.debug:
    #     msg: task1
    # - name: Set up ansible user
    #   ansible.builtin.import_tasks:
    #     file: tasks/users.yml
    # - name: Set up cron job
    #   ansible.builtin.import_tasks:
    # #     file: tasks/cron.yml
    - name: Install packages
      ansible.builtin.import_tasks:
        file: tasks/packages.yml
    - name: Install nix
      ansible.builtin.import_tasks:
        file: tasks/nix.yml
    - name: Install nix home-manager
      ansible.builtin.import_tasks:
        file: tasks/nix-home-manager.yml
# podman...
