---
- name: Local setup playbook
  hosts: localhost
  connection: local
  vars_files:
    - default.config.yml
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    local_home: "{{ lookup('env', 'HOME') }}"
  #   data_dir: "{{ local_home }}/.local/share"
  #   anyenv_root: "{{ data_dir }}/anyenv"
  #   cargo_home: "{{ data_dir }}/cargo"
  #   rustup_home: "{{ data_dir }}/rustup"
  #   os_family: "{{ ansible_os_family | lower }}"
  # environment:
  #   GEM_HOME: "{{ data_dir }}/gem"
  #   RUST_HOME: "{{ rustup_home }}"
  #   CARGO_HOME: "{{ cargo_home }}"
  # was path guilty???
  #   PATH: "{{ ansible_env.PATH }}:{{ anyenv_root }}/bin:/opt/homebrew/bin"
  #   GOPATH: "{{ local_home }}/src/go"

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:

    - name: Get facts about the host
      ansible.builtin.setup:
        gather_subset: all
      register: host_facts

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        ansible_distribution: "{{ host_facts['ansible_facts']['ansible_distribution'] }}"

  roles:
    - role: setup
      # vars:
      #   setup_dir: '/opt/a'
      #   setup_app_port: 5000
      # tags: typeA
    - role: macos
      when: ansible_facts['os_family']|lower == 'darwin'
    - role: debian
      when: ansible_facts['os_family']|lower == 'debian'
