---
- name: Local setup playbook
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

  # vars:
  #   script_runner:
  #     url: "https://install.determinate.systems/nix"
  #     dest: "/opt/determinate-systems/determinate-systems-nix-installer.sh"
  #     checksum: "sha256:101a2169e079fb3b5d92a22040d636025857d0ab2ef6e0fdb0762b26f5580c7d"
  #     executable: true
  tasks:
    - name: Get the username running the deploy
      become: false
      ansible.builtin.command: whoami
      delegate_to: localhost
      register: username_on_the_host
      changed_when: false

    - name: Test
      ansible.builtin.debug:
        var: username_on_the_host
          
    - name: Get facts about the host
      ansible.builtin.setup:
        gather_subset: all
      register: host_facts

    - name: Test
      ansible.builtin.debug:
        var: host_facts['ansible_facts']

    - name: Test
      ansible.builtin.debug:
        var: host_facts['ansible_facts']['ansible_env']['SUDO_USER']

     
    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        # one_fact: host_facts['ansible_facts']['ansible_env']['SUDO_USER']
        one_fact: "{{ host_facts['ansible_facts']['ansible_env']['SUDO_USER'] }}"
    - name: Test
      ansible.builtin.debug:
        var: one_fact


    # - name: Starting playbook
    #   ansible.builtin.debug:
    #     msg: task1
    # - name: Set up ansible user
    #   ansible.builtin.import_tasks:
    #     file: tasks/users.yml
    # - name: Set up cron job
    #   ansible.builtin.import_tasks:
    # #     file: tasks/cron.yml
    - name: Install packages
      ansible.builtin.import_tasks:
        file: tasks/packages.yml
    - name: Install nix
      ansible.builtin.import_tasks:
        file: tasks/nix.yml
    - name: Install nix home-manager
      ansible.builtin.import_tasks:
        file: tasks/nix-home-manager.yml
# podman...
