- name: Install packages
  ansible.builtin.apt:
    # name: "{{packages_to_install}}"
    name:
      - curl
      - aptitude
      - apt-utils
      - ca-certificates
      # Flatpak?
      - gnome-software-plugin-flatpak
      # flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - libfuse2
      - pipx
      - python-is-python3
      # pipx ensurepath
      - ffmpeg
      - libavcodec-extra
      # CAD
      - python3
      - python3-dev
      - python3-pip
      - python3.12-venv
      - python3-numpy
      # podman
      - uidmap # required for pdomap
      # sudo podman image trust set --type accept docker.io
      # # also podman
      - podman
      - podman-compose
      - podman-remote
      - buildah
