- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present

- name: Install Flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present
#     sudo apt install gnome-software-plugin-flatpak

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Set up Flatpak
  community.general.flatpak:
    name: "{{ flatpak_flathub_names }}"
    remote: flathub
    state: present

# Snap packages
- name: Ensure snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present
- name: Install Snap packages
  community.general.snap:
    name:
      - 1password
      - chromium
      - firmware-updater
      # brave, slack, spotify, zoom-client
    state: present
- name: Install Code
  community.general.snap:
    classic: true
    name: code
    state: present
- name: Install VSCode extensions
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
  loop:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - ms-vscode.makefile-tools
    - ms-vscode.js-debug
    - ms-vscode.node-debug2
    - ms-vscode.node-debug
    - ms-vscode.vscode-typescript-tslint-plugin
