- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present

- name: Install Flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Set up Flatpak
  community.general.flatpak:
    name: "{{ flatpak_flathub_names }}"
    remote: flathub
    state: present

- name: Testing cmd
  ansible.builtin.command:
    cmd: ["echo", "Hello, World!"]
    changed_when: false

# avoid using shell module unless you need shell features like pipes, redirection, etc.
# You can also use the 'cmd' parameter instead of free form format.
- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd: ls -l | grep log
    chdir: somedir/
