# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
# https://github.com/geerlingguy/mac-dev-playbook
# https://www.youtube.com/watch?v=1VhPVu5EK5o

# mac and ubuntu
# https://github.com/mdzhang/laptop

- name: Instory does not exist
  vars:
    # brew_prefix: "{{ '/opt/homebrew/bin/brew' if ansible_architecture == 'arm64' else '/usr/local/bin/brew' }}"
    brew_formulae:
      - git
      - wget
      - htop
      - tree
    brew_casks:
      - iterm2
      - visual-studio-code
      - cmake
  block:
    # - name: Ensure Homebrew is installed
    #   ansible.builtin.shell: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    #   # args:
    #   #   creates: "{{ brew_prefix }}"
    #   register: brew_install
    #   changed_when: "'Homebrew' in brew_install.stdout"

    # - name: Ensure brew is in PATH
    #   ansible.builtin.shell: echo 'eval "$({{ brew_prefix }} shellenv)"' >> ~/.zprofile
    #   args:
    #     creates: ~/.zprofile
    #   when: brew_install is changed

    # # Don't wait until the end to run handlers
    # - name: Flush handlers
    #   ansible.builtin.meta: flush_handlers
    # - name: Update brew, formulae and casks
    #   become: true
    #   become_user: "{{ username_on_the_host }}"
    #   community.general.homebrew:
    #     # update_homebrew: true
    #     upgrade_all: true
    #     upgrade_options: ignore-pinned

    - name: Install brew formulae
      become: true
      become_user: "{{ username_on_the_host }}"
      community.general.homebrew:
        name: "{{ brew_formulae }}"
        state: present
        # path: "{{ brew_prefix | dirname }}"

    - name: Install brew casks
      become: true
      become_user: "{{ username_on_the_host }}"
      community.general.homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
        # path: "{{ brew_prefix | dirname }}"
# - name: Using sudo password for installing cask
#   community.general.homebrew_cask:
#     name: wireshark
#     state: present
#     sudo_password: "{{ ansible_become_pass }}"
# handlers:
#   - name: Ensure brew is in PATH
#     ansible.builtin.shell: echo 'eval "$({{ brew_prefix }} shellenv)"' >> ~/.zprofile
#     args:
#       creates: ~/.zprofile
