# Install App from dmg
# https://github.com/sandstorm/macosx-with-ansible/blob/master/tasks/dmg-install.yml
---
# also check out https://github.com/sandstorm/macosx-with-ansible/blob/master/tasks/_base.yml
- ansible.builtin.stat:
    path: /Applications/{{
    cmd: appName }}.app
  delegate_to: localhost
  register: app_exists

- ansible.builtin.command: mkdir -p ./tmp/
  when: app_exists.stat.exists == False

- ansible.builtin.get_url:
    url: "{{"
    dest: ./tmp/{{
    cmd: dmgURL }} appName }}.dmg
  when: app_exists.stat.exists == False

- ansible.builtin.command: hdiutil attach ./tmp/{{ appName }}.dmg -nobrowse -mountpoint ./tmp/{{ appName }}
  when: app_exists.stat.exists == False

- ansible.builtin.shell: cp -aR ./tmp/{{ appName }}/*.app /Applications/{{ appName }}.app
  when: app_exists.stat.exists == False

- ansible.builtin.command: hdiutil detach ./tmp/{{ appName }}/
  when: app_exists.stat.exists == False

- ansible.builtin.command: rm -R ./tmp/
  when: app_exists.stat.exists == False
