---

# # Triggers 'xcode-select --install'
# - name: Install homebrew
#   shell: 'yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
#   args:
#     creates: /opt/homebrew/bin/brew

- name: Ensure homebrew is updated
  community.general.homebrew:
    state: latest
    update_homebrew: true

# - name: Enable Homebrew bundle tap
#   homebrew_tap:
#     name: homebrew/bundle

- name: Install brew formulae
  # become: true
  # become_user: "{{ user_name }}"
  community.general.homebrew:
    name: "{{ homebrew_installed_packages }}"
    state: present

- name: Install a Homebrew cask
  community.general.homebrew_cask:
    name: "{{ homebrew_installed_casks }}"
    state: present

- name: Upgrade all packages
  community.general.homebrew:
    upgrade_all: true
  
- name: Upgrade Homebrew casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Cleanup
  ansible.builtin.shell: 'brew cleanup'

- name: Include common tasks
  ansible.builtin.include_role:
    name: unix