---
# # Triggers 'xcode-select --install'
# - name: Install homebrew
#   shell: 'yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
#   args:
#     creates: /opt/homebrew/bin/brew

# - name: Starting meowmoew
#   ansible.builtin.debug:
#     msg: "{{ macmac.username }}"

- name: Set up OS X Command Line Tools
  ansible.builtin.include_role:
    name: elliotweiser.osx-command-line-tools

- name: Ensure homebrew is updated
  community.general.homebrew:
    state: latest
    update_homebrew: true

# - name: Enable Homebrew bundle tap
#   homebrew_tap:
#     name: homebrew/bundle

- name: Install brew formulae
  # become: true
  # become_user: "{{ user_name }}"
  community.general.homebrew:
    name: "{{ macos.homebrew_installed_packages }}"
    state: present

# requires a lot of password entry...
- name: Install a Homebrew cask
  community.general.homebrew_cask:
    name: "{{ macos.homebrew_installed_casks }}"
    state: present

- name: Upgrade all packages
  community.general.homebrew:
    upgrade_all: true

- name: Upgrade Homebrew casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Cleanup
  ansible.builtin.command:
    argv:
      - brew
      - cleanup
  changed_when: true

# xournal x86 install works, but not arm64
# https://github.com/xournalpp/xournalpp/releases/download/v1.2.7/xournalpp-1.2.7-macOS-X64.dmg
# 1. Install it
# 2. have to remove the quarantine before
# xattr -c /Applications/Xournal++.app
#
# https://ianthehenry.com/posts/how-to-learn-nix/nix-direnv/
# nix direnv
# mkdir -p ~/.config/direnv
# echo 'source ~/.nix-profile/share/nix-direnv/direnvrc' > ~/.config/direnv/direnvrc
# echo 'eval "$(direnv hook zsh)"' >> ~/.zshrc
