---
# Clone to ~/.config/home-manager

# - name: Check if my_package is installed
#   ansible.builtin.shell: which nix
#   # become: true
#   # become_user: "{{ username_on_the_host }}"
#   register: nix_check
#   failed_when: nix_check.rc > 1
#   changed_when: nix_check.rc == 1

- name: Get stats of the FS object
  ansible.builtin.stat:
    path: /nix/var/nix/profiles/default/bin/nix
  register: nix_check

# - name: Starting playbook
#   ansible.builtin.debug:
#     msg: { { nix_check } }

- name: Download determinate nix installer
  ansible.builtin.get_url:
    url: https://install.determinate.systems/nix
    dest: /tmp/determinate-nix.sh
    checksum: sha256:46555f126c17dfe27bb33fedd4dc9b246abf55c147b04a8e929b65e16cd730a6
  when: not nix_check.stat.exists

# https://chaosmail.github.io/programming/2015/03/04/install-deb-packages-in-ansible/
- name: Install nix
  become: true
  ansible.builtin.shell: cat /tmp/determinate-nix.sh | sh -s -- install --determinate --no-confirm --explain
  when: not nix_check.stat.exists
# # Home manager...
# # TODO issues running in an env with nix available?
# # https://chaosmail.github.io/programming/2015/03/04/install-deb-packages-in-ansible/
# - name: Switch home manager
#   become: true
#   become_user: "{{ username_on_the_host }}"
#   ansible.builtin.shell: /nix/var/nix/profiles/default/bin/nix run home-manager -- init --switch
