---
# - name: Only macos
#   when: is_macos
#   ansible.builtin.debug:
#     msg: to do macos

# - name: Pls no
#   when: is_debian
#   ansible.builtin.debug:
#     msg: do not print this

- name: Set up Joplin
  when: unix.install_joplin
  ansible.builtin.import_tasks: joplin.yml

- name: Set up VSCode
  when: unix.install_vscode
  ansible.builtin.import_tasks: vscode.yml

- name: Set up SSH
  ansible.builtin.import_tasks: ssh.yml

- name: Set up git
  ansible.builtin.import_tasks: git.yml

- name: Set up nix
  when: unix.install_nix
  ansible.builtin.import_tasks: nix.yml

# xournal
# - name: Get gogs latest tag
#   github_release:
#     user: gogs
#     repo: gogs
#     action: latest_release
#   register: gogs_latest

# - name: Grab gogs latest binaries
#   unarchive:
#     src: "https://github.com/gogs/gogs/releases/download/{{ gogs_latest['tag'] }}/gogs_{{ gogs_latest['tag'] | regex_replace('^v','') }}_linux_amd64.zip"
#     dest: /usr/local/bin
#     remote_src: true

# https://talonvoice.com/update/qyO6k0Y0jHOeI94q51eTKV/Talon-115-0.4.0-950-bd10.dmg

# todo only if ~/.talon/user exists, and is empty!!!
# - name: Git checkout
#   ansible.builtin.git:
#     repo: "git@github.com:imochoa/talon-user-dir.git"
#     dest: "{{ user_name }}/.talon/user"
#     version: "master"
#  git clone git@github.com:imochoa/talon-user-dir.git ~/.talon/user
# git submodule update --init --recursive

# wacom Download
# https://support.wacom.asia/tw/content/macos-driver-6338-3
