# TODO: copy .ssh dir

# - name: Add a host in the configuration
#   community.general.ssh_config:
#     user: akasurde
#     host: "example.com"
#     add_keys_to_agent: true
#     hostname: "github.com"
#     identity_file: "/home/akasurde/.ssh/id_rsa"
#     port: "2223"
#     state: present
#     other_options:
#       serveraliveinterval: "30"

# - name: Copy local ~/.ssh to remote user
#   hosts: all
#   become: yes
#   tasks:
- name: Ensure remote .ssh directory exists
  file:
    path: /home/{{ username_on_the_host }}/.ssh
    state: directory
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"
    mode: "0700"
#     - name: Copy SSH directory to remote user
#       ansible.posix.synchronize:
#         src: ~/.ssh/
#         dest: /home/your_user/.ssh/
#         recursive: yes
#         rsync_opts:
#           - "--chmod=700"
#       delegate_to: localhost

#     - name: Set correct permissions on private key
#       file:
#         path: /home/your_user/.ssh/id_rsa
#         owner: your_user
#         group: your_user
#         mode: '0600'
#       when: ansible_facts['os_family'] != 'Windows'

#     - name: Set correct permissions on public key
#       file:
#         path: /home/your_user/.ssh/id_rsa.pub
#         owner: your_user
#         group: your_user
#         mode: '0644'
#       when: ansible_facts['os_family'] != 'Windows'

# add to ssh group?
- name: Ensure correct SSH directory permissions
  ansible.builtin.file:
    path: "/home/{{ username_on_the_host }}/.ssh"
    state: directory
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"
    mode: "0700"

- name: Start SSH agent and set environment variables
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK; SSH_AGENT_PID=$SSH_AGENT_PID"
  register: ssh_agent_output
  changed_when: false # Avoids reporting "changed" on every run

- name: Set SSH agent environment variables
  ansible.builtin.set_fact:
    ssh_auth_sock: "{{ ssh_agent_output.stdout | regex_search('SSH_AUTH_SOCK=([^;]+)') }}"
    ssh_agent_pid: "{{ ssh_agent_output.stdout | regex_search('SSH_AGENT_PID=([^;]+)') }}"

- name: Add SSH private key to agent
  ansible.builtin.shell: |
    ssh-add /path/to/private_key  # Replace with your key path
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
  no_log: true # Hides sensitive key paths from logs

- name: Clone a repo using SSH agent
  ansible.builtin.git:
    repo: "{{ AnsiblePullRepo }}"
    version: master
    update: yes
    dest: "/path/to/clone"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"

- name: List keys in agent
  ansible.builtin.shell: "ssh-add -l"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
